I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/splash.rpy", line 2, in script
    init -100 python:
  File "game/splash.rpy", line 7, in <module>
    renpy.error("DDLC archive files not found in /game folder. Check installation and try again.")
Exception: DDLC archive files not found in /game folder. Check installation and try again.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-7.0.0-sdk\renpy\bootstrap.py", line 306, in bootstrap
    renpy.main.main()
  File "D:\renpy-7.0.0-sdk\renpy\main.py", line 423, in main
    renpy.game.context().run(node)
  File "game/splash.rpy", line 2, in script
    init -100 python:
  File "D:\renpy-7.0.0-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-7.0.0-sdk\renpy\python.py", line 1912, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/splash.rpy", line 7, in <module>
    renpy.error("DDLC archive files not found in /game folder. Check installation and try again.")
  File "D:\renpy-7.0.0-sdk\renpy\exports.py", line 2242, in error
    _error_handlers[-1](msg)
  File "D:\renpy-7.0.0-sdk\renpy\exports.py", line 2227, in _error
    raise Exception(msg)
Exception: DDLC archive files not found in /game folder. Check installation and try again.

Windows-7-6.1.7601-SP1
Ren'Py 7.0.0.196
 
Fri Jun 09 23:23:53 2023
